Vagrant.require_version ">= 2.0.1"

Vagrant.configure("2") do |config|

  # config.vm.box  (string) - This configures what box the machine will be
  # brought up against. The value here should be the name of an installed box
  # or a shorthand name of a box in HashiCorp's Vagrant Cloud.
  config.vm.box = "ubuntu/bionic64"

  # config.vm.box_check_update (boolean) - If true, Vagrant will check
  # for updates to the configured box on every vagrant up. If an update is found,
  # Vagrant will tell the user. By default this is true. Updates will only be
  # checkedfor boxes that properly support updates (boxes from HashiCorp's Vagrant
  # Cloud or some other versioned box).
  config.vm.box_check_update = true

  # config.vm.hostname (string) - The hostname the machine should have. Defaults to nil.
  # If nil, Vagrant will not manage the hostname. If set to a string, the hostname will
  # be set on boot. If set, Vagrant will update /etc/hosts on the guest with the configured
  #  hostname.
  config.vm.hostname = "gRPCoverSDKLT-vm"

  # config.vm.communicator (string) - The communicator type to use to connect to the guest box.
  # By default this is "ssh", but should be changed to "winrm" for Windows guests.
  # config.vm.communicator = "ssh"

  # config.vm.boot_timeout (integer) - The time in seconds that Vagrant will wait
  # for the machine to boot and be accessible. By default this is 300 seconds.
  config.vm.boot_timeout = 360

  # config.vm.graceful_halt_timeout (integer) - The time in seconds that Vagrant
  # will wait for the machine to gracefully halt when vagrant halt is called.
  # Defaults to 60 seconds.
  # config.vm.graceful_halt_timeout = 60

  config.vm.provider "virtualbox" do |vb|
    # allocating 4G of ram for this vm
    vb.memory = 4096

    # running in headless mode.
    vb.gui = false

    # set the disksize as 10GB
    #config.disksize.size = '10GB'

    # allocating 4 CPU's
    vb.cpus = 4

    # assiningg virtual machine name
    vb.name = "gRPCoverSDKLT-vm"

    # synchronzie the time clock
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end

  # syncing the uplevel folders
  config.vm.synced_folder "../", "/home/vagrant/gRPCoverSDKLT"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # config.vm.network - Configures networks on the machine.
  # networking for port forwarding
  # forward host port 50051 to guest port 50051
  config.vm.network "private_network", ip: "192.168.12.2"
  config.vm.network "forwarded_port", guest: 50051, host: 50051

  # provision the shell script
  config.vm.provision "shell", path: "../scripts/install_deps.sh"

end
